# SmartDNS default configuration for fnOS

bind [::]:6580
bind-tcp [::]:6580

cache-size 4096
prefetch-domain yes
serve-expired yes

server 114.114.114.114
server 119.29.29.29
server 223.5.5.5
server 8.8.8.8
server 1.1.1.1

